version: "3"
services:
  garnize-on-juice:
    build: .
    ports:
      - "9999:9999"
    networks:
      - payment-processor
    environment:
      - PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "350MB"

networks:
  payment-processor:
    name: payment-processor
    driver: bridge
